from typing import Callable, Optional

BOARD: int
IN: int
BOTH: int
PUD_UP: int
PUD_DOWN: int
PUD_OFF: int

def add_event_detect(channel: int, edge: int, callback: Optional[Callable[[int], None]] = None) -> None: ...
def input(channel: int) -> bool: ...
def setmode(new_mode: int) -> None: ...
def setup(channel: int, direction: int, pull_up_down: Optional[int] = None, initial: Optional[float] = None) -> None: ...
def remove_event_detect(channel: int) -> None: ...
