from typing import Callable


BOARD: int
IN: int
BOTH: int
PUD_UP: int
PUD_DOWN: int
PUD_OFF: int

def add_event_detect(channel: int, edge: int, callback: Callable[[int], None] = None) -> None: ...
def input(channel: int) -> bool: ...
def setmode(new_mode: int) -> None: ...
def setup(channel: int, direction: int, pull_up_down: int = None, initial: float = None) -> None: ...
def remove_event_detect(channel: int) -> None: ...
