# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: TestPyPI

on:
  push:
    branches:
        - main
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    uses: ./.github/workflows/python-package.yml
    with:
      publishes: true
      artifact_name: 'test_package'

  deploy:
    name: Deploy to Test PyPI
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ jobs.build_and_test.artifact_name }}
        path: ./

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --skip-existing --repository testpypi dist/*
