# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: TestPyPI

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
        - main

jobs:
  build_and_test:
    uses: ./.github/workflows/python-package.yml
    name: Build and test package
    with:
      publishes: true
      artifact_name: 'test_package'

  deploy:
    uses: ./.github/workflows/reusable_publish.yml
    name: Deploy to Test PyPI
    needs: build_and_test
    with:
      artifact_name: 'test_package'
      repo_name: 'testpypi'
      pypi_username: ${{ secrets.TESTPYPI_USERNAME }}
      pypi_password: ${{ secrets.TESTPYPI_PASSWORD }}
