# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package (TestPyPI)

on:
  push:
    branches:
        - main

jobs:
  build:
    name: Build and test package
    uses: 2franix/rpi-controls/.github/workflows/python-package.yml

  deploy:
    name: Build and deploy python package to Test PyPI

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt install tox
        python -m pip install --upgrade pip
        python -m pip install build
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        tox
        python -m build
        twine upload --skip-existing --repository testpypi dist/*
