# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
      publishes:
        description: 'Whether to publish the artifact at the end of the build'
        default: false
        required: false
        type: boolean
      artifact_name:
        description: 'Name of the artifact to publish'
        required: true
        type: string

jobs:
  build:
    name: Build python package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install tox npm
        npm i -g pyright

    - name: Test with tox
      run: |
        tox

    - uses: actions/upload-artifact@v3
      if: ${{ inputs.publishes }}
      with:
        name: ${{ inputs.artifact_name }}
        path: dist/*
